INSERT INTO persons VALUES (DEFAULT, 'George', 'V' , 'George Frederick Ernest Albert', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Male', '1865-06-03' , '1936-01-20');
INSERT INTO persons VALUES (DEFAULT, 'Mary', NULL , 'Victoria Mary Augusta Louise Olga Pauline Claudine Agnes', 'Teck' , NULL , 'Female', '1867-05-26' , '1953-03-24');
INSERT INTO persons VALUES (DEFAULT, 'Edward', 'VIII' , 'Edward Albert Christian George Andrew Patrick David', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Male', '1894-06-23' , '1972-03-28');
INSERT INTO persons VALUES (DEFAULT, 'George', 'VI' , 'Albert Frederick Arthur George', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Male', '1895-12-14' , '1952-02-06');
INSERT INTO persons VALUES (DEFAULT, 'Elizabeth', 'I' , 'Elizabeth Angela Marguerite Bowes-Lyon', 'Windsor' , 'Bowes-Lyon' , 'Female', '1900-08-04' , '2002-03-30');
INSERT INTO persons VALUES (DEFAULT, 'Mary', NULL , 'Victoria Alexandra Alice Mary', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Female', '1897-04-25' , '1965-03-28');
INSERT INTO persons VALUES (DEFAULT, 'Henry', NULL , 'Henry William Frederick Albert', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Male', '1900-03-31' , '1974-06-10');
INSERT INTO persons VALUES (DEFAULT, 'Alice', NULL , 'Alice Christabel', 'Montagu Douglas Scott' , NULL , 'Female', '1901-12-25' , '2004-10-29');
INSERT INTO persons VALUES (DEFAULT, 'George', NULL , 'George Edward Alexander Edmund', 'Windsor' , 'Saxe-Coburg and Gotha' , 'Male', '1902-12-20' , '1942-08-25');
INSERT INTO persons VALUES (DEFAULT, 'Marina', NULL , 'Marina', 'Glücksburg' , NULL , 'Female', '1906-12-13' , '1968-08-30');
INSERT INTO persons VALUES (DEFAULT, 'John', NULL , 'John Charles Francis', 'Windsor' , NULL , 'Male', '1905-07-12' , '1919-01-18');
INSERT INTO persons VALUES (DEFAULT, 'Elizabeth', 'II' , 'Elizabeth Alexandra Mary', 'Windsor' , NULL , 'Female', '1926-04-21' , '2022-09-08');
INSERT INTO persons VALUES (DEFAULT, 'Philip', NULL , 'Philip', 'Mountbatten' , 'Glücksburg' , 'Male', '1921-06-10' , '2021-04-09');
INSERT INTO persons VALUES (DEFAULT, 'Margaret', NULL , 'Margaret Rose', 'Windsor' , NULL , 'Female', '1930-08-21' , '2002-02-09');
INSERT INTO persons VALUES (DEFAULT, 'William', NULL , 'William Henry Andrew Frederick', 'Windsor' , NULL , 'Male', '1941-12-18' , '1972-08-28');
INSERT INTO persons VALUES (DEFAULT, 'Richard', NULL , 'Richard Alexander Walter George', 'Windsor' , NULL , 'Male', '1944-08-26' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Birgitte', NULL , 'Birgitte Eva', 'Windsor' , NULL , 'Female', '1946-06-20' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Edward', NULL , 'Edward George Nicholas Paul Patrick', 'Windsor' , NULL , 'Male', '1935-10-09' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Katharine', NULL , 'Katharine Lucy Mary', 'Windsor' , NULL , 'Female', '1933-02-22' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Alexandra', NULL , 'Alexandra Helen Elizabeth Olga Christabel', 'Windsor' , NULL , 'Female', '1936-12-25' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Michael', NULL , 'Michael George Charles Franklin', 'Windsor' , NULL , 'Male', '1942-07-04' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Michael', NULL , 'Marie-Christine Anna Agnes Hedwig Ida', 'Windsor' , 'Reibnitz' , 'Female', '1945-01-15' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Charles', 'III' , 'Charles Philip Arthur George', 'Windsor' , NULL , 'Male', '1948-11-14' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Diana', NULL , 'Diana Frances', 'Windsor' , 'Spencer' , 'Female', '1961-07-01' , '1997-08-31');
INSERT INTO persons VALUES (DEFAULT, 'Camilla', NULL , 'Camilla Rosemary', 'Windsor' , NULL , 'Female', '1947-07-17' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Anne', NULL , 'Anne Elizabeth Alice Louise', 'Windsor' , NULL , 'Female', '1950-08-15' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Andrew', NULL , 'Andrew Albert Christian Edward', 'Windsor' , NULL , 'Male', '1960-02-19' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Sarah', NULL , 'Sarah Margaret', 'Windsor' , NULL , 'Female', '1959-10-15' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Edward', NULL , 'Edward Antony Richard Louis', 'Windsor' , NULL , 'Male', '1964-03-10' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Sophie', NULL , '	Sophie Helen', 'Windsor' , NULL , 'Female', '1965-01-20' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'William', NULL , 'William Arthur Philip Louis', 'Windsor' , NULL , 'Male', '1982-06-21' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Catherine', NULL , 'Catherine Elizabeth', 'Middleton' , NULL , 'Female', '1982-01-09' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Harry', NULL , 'Henry Charles Albert David', 'Windsor' , NULL , 'Male', '1984-09-15' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Meghan', NULL , 'Rachel Meghan', 'Windsor' , NULL , 'Female', '1981-08-04' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Beatrice', NULL , 'Beatrice Elizabeth Mary', 'Windsor' , NULL , 'Female', '1988-08-08' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Eugenie', NULL , 'Eugenie Victoria Helena', 'Windsor' , NULL , 'Female', '1990-03-23' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Louise ', NULL , 'Louise Alice Elizabeth Mary', 'Windsor' , NULL , 'Female', '2003-11-08' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'James', NULL , 'James Alexander Philip Theo', 'Windsor' , NULL , 'Male', '2007-12-17' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'George', NULL , 'George Alexander Louis', 'Windsor' , NULL , 'Male', '2013-07-22' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Charlotte', NULL , 'Charlotte Elizabeth Diana', 'Windsor' , NULL , 'Female', '2015-05-02' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Louis', NULL , 'Louis Arthur Charles', 'Windsor' , NULL , 'Male', '2018-04-23' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Archie', NULL , 'Archie Harrison', 'Windsor' , NULL , 'Male', '2019-03-06' , NULL);
INSERT INTO persons VALUES (DEFAULT, 'Lilibet', NULL , 'Lilibet Diana', 'Windsor' , NULL , 'Female', '2021-06-04' , NULL);